import {Trash2,Plus,Minus} from 'lucide-react';
import type {Line,Project} from './types';
import {useText,CategoryIcon,NumberField,Field,Toggle,Note,Button} from './ui';
import {calculateProject} from './engine';
export function PlanLines({lines,onChange,editable=false}:{lines:Line[];onChange:(lines:Line[])=>void;editable?:boolean}){
 const {t,money,productName}=useText();const change=(id:string,key:keyof Line,value:unknown)=>onChange(lines.map(l=>l.id===id?{...l,[key]:value}:l));
 return <div className="sf-plan-lines">{lines.map(l=><article className={`sf-plan-line ${editable?'expanded':''}`} key={l.id}>
  <div className="sf-line-main"><div className="sf-line-icon"><CategoryIcon category={l.product.category}/></div><div className="sf-line-name"><h3>{productName(l.product)}</h3><small>{l.product.phase?`${l.product.phase}${t('-fase','-phase')} · `:''}{l.price===null?t('Prijs ontbreekt','Missing price'):money(l.price)} {t('per stuk','each')}</small></div><button className="sf-icon-button" aria-label={`${t('Verwijder','Remove')} ${productName(l.product)}`} onClick={()=>onChange(lines.filter(x=>x.id!==l.id))}><Trash2 size={16}/></button></div>
  <div className="sf-between">{l.product.category==='extra'?<div className="sf-quantity"><button disabled={l.quantity<=1} aria-label={`${t('Minder','Fewer')} ${productName(l.product)}`} onClick={()=>change(l.id,'quantity',l.quantity-1)}><Minus size={13}/></button><span aria-label={t('Aantal','Quantity')}>{l.quantity}</span><button disabled={l.quantity>=20} aria-label={`${t('Meer','More')} ${productName(l.product)}`} onClick={()=>change(l.id,'quantity',l.quantity+1)}><Plus size={13}/></button></div>:<small>{t('1 compleet systeem','1 complete system')}</small>}<strong>{l.price===null?'—':money(l.price*l.quantity)}</strong></div>
  {editable&&<details open={l.price===null}><summary>{t('Prijs, subsidie & extra instellingen','Price, subsidy & additional settings')}</summary><div className="sf-fields sf-top"><NumberField label={t('Prijs per stuk incl. btw (€)','Unit price incl. VAT (€)')} value={l.price} optional onChange={v=>change(l.id,'price',v)}/><NumberField label={t('Subsidie per stuk (€)','Subsidy per unit (€)')} value={l.subsidy} max={l.price??1e8} onChange={v=>change(l.id,'subsidy',v??0)}/><NumberField label={t('Onderhoud / abonnement per stuk (€/jaar)','Maintenance / subscription per unit (€/year)')} value={l.annualCost} onChange={v=>change(l.id,'annualCost',v??0)}/>{l.product.category==='extra'&&<NumberField label={t('Handmatig onderbouwd voordeel (€/jaar per stuk)','Manually supported benefit (€/year per unit)')} value={l.manualBenefit} onChange={v=>change(l.id,'manualBenefit',v??0)} help={t('Laat op 0 voor installatie of accessoires zonder eigen besparing.','Leave at 0 for installation or accessories without separate savings.')}/>}</div>{l.product.category==='heatpump'&&<p className="sf-small">{t('Subsidie is een indicatie uit de prijslijst. Controleer meldcode en voorwaarden bij','Subsidy is a price-list estimate. Check the product code and conditions with')} <a href="https://www.rvo.nl/subsidies-financiering/isde/woningeigenaren/warmtepomp" target="_blank" rel="noreferrer">RVO</a>.</p>}</details>}
 </article>)}</div>;
}
export function PlanSummary({project,onChange,onNext}:{project:Project;onChange:(p:Project)=>void;onNext:()=>void}){
 const {t,money,num}=useText();const r=calculateProject(project);
 return <aside className="sf-plan-summary"><div className="sf-between"><span className="sf-eyebrow">{t('Jouw energieplan','Your energy plan')}</span><span className="sf-count">{project.lines.reduce((n,l)=>n+l.quantity,0)}</span></div>
  {project.lines.length===0?<div className="sf-empty"><Plus size={28}/><h3>{t('Maak het jouw systeem.','Make it your system.')}</h3><p>{t('Voeg producten toe. Hier zie je direct wat er bij komt.','Add products to see how your plan changes.')}</p></div>:<PlanLines lines={project.lines} onChange={lines=>onChange({...project,lines})}/>}
  <dl className="sf-totals"><div><dt>{t('Producten incl. btw','Products incl. VAT')}</dt><dd>{money(r.gross)}</dd></div>{r.subsidy>0&&<div><dt>{t('Indicatieve subsidie','Estimated subsidy')}</dt><dd>− {money(r.subsidy)}</dd></div>}<div className="sf-total"><dt>{t('Netto investering','Net investment')}</dt><dd>{r.missing.length?t('Onvolledig','Incomplete'):money(r.investment)}</dd></div></dl>
  {r.missing.length>0&&<Note warning>{t('Vul de ontbrekende prijzen in bij stap 3.','Enter missing prices in step 3.')}</Note>}
  {project.lines.length>0&&<div className="sf-side-benefit"><span>{t('Verwacht voordeel / jaar','Estimated benefit / year')}</span><strong>{r.valid?money(r.annual):'—'}</strong><small>{t('Terugverdientijd','Payback')}: {r.payback===null?'—':`${num(r.payback)} ${t('jaar','years')}`}</small></div>}
  <Button onClick={onNext} disabled={!project.lines.length}>{t('Bekijk mijn overzicht','View my summary')} <span>→</span></Button><p className="sf-small">{t('Indicatie op basis van je invoer. Geen offerte of gegarandeerd rendement.','Estimate based on your inputs. Not a quotation or guaranteed return.')}</p>
 </aside>;
}
export function FinanceFields({project,onChange}:{project:Project;onChange:(p:Project)=>void}){
 const {t,money}=useText();const r=calculateProject(project);const f=project.finance;const set=(key:keyof Project['finance'],value:number|boolean)=>onChange({...project,finance:{...f,[key]:value}});
 return <section className="sf-panel"><Toggle label={t('Financiering doorrekenen','Calculate financing')} checked={f.enabled} onChange={v=>set('enabled',v)} help={t('Een losse rekenhulp; geen leningaanvraag of toezegging.','A separate calculator, not a loan application or approval.')}/>{f.enabled&&<><div className="sf-fields sf-top"><NumberField label={t('Gewenst leenbedrag (€)','Requested loan amount (€)')} value={f.amount} onChange={v=>set('amount',v??0)}/><NumberField label={t('Jaarlijkse debetrente (%)','Annual borrowing rate (%)')} value={f.rate} max={30} onChange={v=>set('rate',v??0)}/><NumberField label={t('Looptijd (jaren)','Term (years)')} value={f.years} step={1} min={1} max={30} onChange={v=>set('years',v??10)}/></div><div className="sf-finance-figures"><div><span>{t('Berekend leenbedrag','Calculated loan amount')}</span><strong>{money(r.financed)}</strong></div><div><span>{t('Aflossing + rente / maand','Principal + interest / month')}</span><strong>{money(r.monthlyPayment,2)}</strong></div><div><span>{t('Voordeel min maandlast','Benefit less monthly payment')}</span><strong>{money(r.monthlyNet,2)}</strong></div></div><p className="sf-small">{t('Leenbedrag begrensd op de netto investering. Totale aflossing + rente:','Loan amount capped at net investment. Total principal + interest:')} {money(r.loanTotal,2)}. {t('De terugverdientijd van het systeem is zonder financieringskosten.','System payback excludes financing costs.')}</p></>}</section>;
}
