import {useState,useMemo} from 'react';
import {Search,Plus,SlidersHorizontal,Pencil,Check,RefreshCw} from 'lucide-react';
import type {Product,Category} from './types';
import {catalog,grossPrice} from './catalog';
import {useText,useCategories,CategoryIcon,Button,NumberField,Field,Modal,Note} from './ui';
export function ProductEditor({initial,onSave,onClose}:{initial?:Product;onSave:(p:Product)=>void;onClose:()=>void}){
 const {t}=useText();const cats=useCategories();
 const [p,setP]=useState<Product>(initial??{id:crypto.randomUUID(),name:'',nameEn:'',brand:'',category:'extra',price:null,vat:21,priceBasis:'inclusive'});
 const set=(key:keyof Product,value:unknown)=>setP({...p,[key]:value});
 return <Modal title={initial?t('Product bewerken','Edit product'):t('Eigen product toevoegen','Add your own product')} onClose={onClose}><form className="sf-form" onSubmit={e=>{e.preventDefault();onSave({...p,name:p.name.trim(),nameEn:p.nameEn?.trim()||p.name.trim(),brand:p.brand.trim()||'SolarFast'});onClose();}}>
  <div className="sf-fields"><Field label={t('Productnaam','Product name')}><input required maxLength={160} value={p.name} onChange={e=>set('name',e.target.value)}/></Field><Field label={t('Engelse naam (optioneel)','English name (optional)')}><input maxLength={160} value={p.nameEn??''} onChange={e=>set('nameEn',e.target.value)}/></Field><Field label={t('Merk','Brand')}><input maxLength={80} value={p.brand} onChange={e=>set('brand',e.target.value)}/></Field><Field label={t('Categorie','Category')}><select value={p.category} onChange={e=>set('category',e.target.value)}>{Object.entries(cats).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></Field>
  <NumberField label={t('Prijs (€)','Price (€)')} value={p.price} optional onChange={v=>set('price',v)}/><Field label={t('Prijs is','Price is')}><select value={p.priceBasis} onChange={e=>set('priceBasis',e.target.value)}><option value="inclusive">{t('Inclusief btw','VAT inclusive')}</option><option value="exclusive">{t('Exclusief btw','VAT exclusive')}</option></select></Field><NumberField label={t('Btw (%)','VAT (%)')} value={p.vat} max={100} onChange={v=>set('vat',v??0)}/>
  {p.category==='battery'&&<NumberField label={t('Capaciteit (kWh)','Capacity (kWh)')} value={p.capacity??0} onChange={v=>set('capacity',v??0)}/>}
  {(p.category==='battery'||p.category==='charger')&&<Field label={t('Aansluiting','Connection')}><select value={p.phase??3} onChange={e=>set('phase',Number(e.target.value))}><option value={1}>{t('1-fase','Single-phase')}</option><option value={3}>{t('3-fase','Three-phase')}</option></select></Field>}
  {p.category==='solar'&&<><NumberField label={t('Aantal panelen per pakket','Panels per package')} value={p.panels??1} min={1} max={1000} step={1} onChange={v=>set('panels',v??1)}/><NumberField label={t('Vermogen per paneel (Wp)','Output per panel (Wp)')} value={p.watts??475} min={1} onChange={v=>set('watts',v??475)}/></>}
  {p.category==='heatpump'&&<><Field label={t('Uitvoering','Type')}><select value={p.heating??'hybrid'} onChange={e=>set('heating',e.target.value)}><option value="hybrid">{t('Hybride','Hybrid')}</option><option value="electric">All-electric</option></select></Field><Field label={t('Vermogen (kW)','Capacity (kW)')}><input value={p.power??''} onChange={e=>set('power',e.target.value)} maxLength={30}/></Field><NumberField label={t('Indicatieve subsidie (€)','Estimated subsidy (€)')} value={p.subsidy??0} onChange={v=>set('subsidy',v??0)}/></>}
  </div><Note>{t('Je wijzigingen blijven in deze browser bewaard. Exporteer je plan om de catalogus mee te nemen. Bestaande offerteposten veranderen niet automatisch.','Changes are saved in this browser. Export your plan to keep the catalogue. Existing quote lines do not change automatically.')}</Note><div className="sf-actions"><Button secondary onClick={onClose}>{t('Annuleren','Cancel')}</Button><Button type="submit">{t('Product opslaan','Save product')}</Button></div>
 </form></Modal>;
}
export function Products({customProducts,onSaveProduct,onAdd,selectedIds,takenCategories=[],compact=false,initialCategory='battery'}:{customProducts:Product[];onSaveProduct:(p:Product)=>void;onAdd:(p:Product)=>void;selectedIds:string[];takenCategories?:Category[];compact?:boolean;initialCategory?:Category}){
 const {t,money,num,productName}=useText();const cats=useCategories();
 const [category,setCategory]=useState<Category>(initialCategory);const [search,setSearch]=useState('');const [brand,setBrand]=useState('');const [phase,setPhase]=useState('');const [panels,setPanels]=useState('');const [limit,setLimit]=useState(9);const [editing,setEditing]=useState<Product|null|undefined>();const [manage,setManage]=useState(false);
 const all=useMemo(()=>{const map=new Map(catalog.map(p=>[p.id,p]));customProducts.forEach(p=>map.set(p.id,p));return [...map.values()];},[customProducts]);
 const brands=[...new Set(all.filter(p=>p.category===category).map(p=>p.brand))];
 const items=all.filter(p=>p.category===category&&(!brand||p.brand===brand)&&(!phase||p.phase===Number(phase))&&(!panels||p.panels===Number(panels))&&`${p.name} ${p.nameEn??''} ${p.brand}`.toLowerCase().includes(search.toLowerCase()));
 const switchCategory=(c:Category)=>{setCategory(c);setBrand('');setPhase('');setPanels('');setLimit(9);};
 return <div className="sf-product-section">
  {!compact&&<div className="sf-section-heading"><span className="sf-eyebrow">{t('Één woning. Alle mogelijkheden.','One home. Every possibility.')}</span><h1>{t('Bouw aan jouw energieplan.','Build your energy plan.')}</h1><p>{t('Alle producten en prijslijsten op één plek. Voeg toe aan je plan en bekijk wat de combinatie oplevert.','Every product and price list in one place. Add to your plan and explore the combined impact.')}</p></div>}
  <div className="sf-tabs" aria-label={t('Productcategorieën','Product categories')}>{Object.entries(cats).map(([key,label])=><button key={key} aria-pressed={category===key} className={category===key?'active':''} onClick={()=>switchCategory(key as Category)}><CategoryIcon category={key as Category} size={19}/>{label}<small>{all.filter(p=>p.category===key).length}</small></button>)}</div>
  <div className="sf-product-tools"><label className="sf-search"><Search size={18}/><input aria-label={t('Zoek product','Search products')} placeholder={t('Zoek op merk, model of capaciteit…','Search brand, model or capacity…')} value={search} onChange={e=>{setSearch(e.target.value);setLimit(9);}}/></label><select aria-label={t('Filter merk','Filter brand')} value={brand} onChange={e=>{setBrand(e.target.value);setLimit(9);}}><option value="">{t('Alle merken','All brands')}</option>{brands.map(b=><option key={b}>{b}</option>)}</select>{(category==='battery'||category==='charger')&&<select aria-label={t('Filter aansluiting','Filter connection')} value={phase} onChange={e=>{setPhase(e.target.value);setLimit(9);}}><option value="">{t('Alle aansluitingen','All connections')}</option><option value="1">{t('1-fase','Single-phase')}</option><option value="3">{t('3-fase','Three-phase')}</option></select>}{category==='solar'&&<select aria-label={t('Aantal panelen','Panel count')} value={panels} onChange={e=>{setPanels(e.target.value);setLimit(9);}}><option value="">{t('Alle aantallen','All panel counts')}</option>{Array.from({length:17},(_,i)=><option key={i} value={i+4}>{i+4} {t('panelen','panels')}</option>)}</select>}</div>
  <div className="sf-between sf-catalog-meta"><span>{items.length} {t('producten','products')} · {t('prijzen incl. btw, vóór subsidie','prices incl. VAT, before subsidy')}</span><button className="sf-text-button" onClick={()=>setManage(!manage)}><SlidersHorizontal size={15}/>{manage?t('Beheer sluiten','Close management'):t('Catalogus beheren','Manage catalogue')}</button></div>
  {category==='solar'&&<Note>{t('LONGi 470/475 Wp glas/glas. De berekening gebruikt 475 Wp; dit kun je per product aanpassen. Meer dan 20 panelen? Voeg een eigen pakket toe. Pakketten “op batterij” vereisen een geschikte omvormer.','LONGi 470/475 Wp glass/glass. Calculations use 475 Wp, editable per product. More than 20 panels? Add a custom package. Battery-connected packages require a compatible inverter.')}</Note>}
  <div className={`sf-products-grid ${compact?'compact':''}`}>{items.slice(0,limit).map(p=>{const price=grossPrice(p);const selected=selectedIds.includes(p.id);return <article className="sf-product" key={p.id}><div className="sf-between"><span className="sf-product-brand">{p.brand}</span><div className="sf-product-icon"><CategoryIcon category={p.category}/></div></div><h3>{productName(p)}</h3><div className="sf-tags">{p.phase&&<span>{p.phase}{t('-fase','-phase')}</span>}{p.capacity&&<span>{num(p.capacity,2)} kWh</span>}{p.panels&&<span>{num(p.panels*(p.watts??475)/1000,2)} kWp</span>}{p.power&&<span>{p.power} kW</span>}{p.heating&&<span>{p.heating==='electric'?'All-electric':t('Hybride','Hybrid')}</span>}{p.backup&&<span>{t('Back-up volgens prijslijst','Backup per price list')}</span>}{p.connection==='Frank'&&<span>Frank</span>}</div><div className="sf-product-bottom"><small>{price===null?t('Prijs op aanvraag','Price on request'):t('Investering','Investment')}</small><strong>{price===null?'—':money(price,price%1?2:0)}</strong>{p.priceBasis==='exclusive'&&<small>{money(p.price??0,2)} {t('excl. btw','excl. VAT')} + {p.vat}%</small>}{p.subsidy!==undefined&&<small className="sf-green">{t('Indicatieve subsidie','Estimated subsidy')}: {money(p.subsidy)}</small>}<div className="sf-actions"><Button onClick={()=>onAdd(p)} disabled={selected&&p.category!=='extra'} secondary>{selected?<Check size={17}/>:takenCategories.includes(p.category)?<RefreshCw size={17}/>:<Plus size={17}/>} {selected&&p.category!=='extra'?t('In je plan','In your plan'):selected?t('Aantal verhogen','Increase quantity'):takenCategories.includes(p.category)?t('Vervang dit onderdeel','Replace this module'):t('Toevoegen','Add to plan')}</Button>{manage&&<button className="sf-icon-button" aria-label={`${t('Bewerk','Edit')} ${productName(p)}`} onClick={()=>setEditing(p)}><Pencil size={17}/></button>}</div></div></article>;})}
  <button className="sf-product sf-custom-card" onClick={()=>setEditing(null)}><span className="sf-product-icon"><Plus/></span><h3>{t('Iets anders toevoegen?','Something else to add?')}</h3><p>{t('Een eigen product, installatie, meterkast, service of een groter pakket.','Your own product, installation, meter box, service or a larger package.')}</p><span className="sf-green">{t('Eigen product aanmaken','Create custom product')} →</span></button></div>
  {items.length===0&&<p className="sf-note">{t('Geen producten gevonden. Pas je filters aan of voeg een eigen product toe.','No products found. Adjust your filters or create a custom product.')}</p>}
  {items.length>limit&&<div className="sf-center"><Button secondary onClick={()=>setLimit(limit+12)}>{t('Meer producten tonen','Show more products')} ({items.length-limit})</Button></div>}
  <details className="sf-source-note"><summary>{t('Herkomst en prijsafspraken','Source and pricing notes')}</summary><p>{t('Overgenomen uit je SolarFast-document. Bij dubbele prijzen is de gedetailleerde prijslijst gebruikt. Batterijen en panelen zijn voorlopig behandeld als consumentenprijzen inclusief btw; controleer installatie en inbegrepen werkzaamheden. Warmtepompen en Zaptec zijn omgerekend met 21% btw. Enkele eindprijzen in het document bevatten rekenverschillen; hier geldt prijs excl. btw × 1,21 − subsidie. Subsidies zijn indicaties uit het document.','Imported from your SolarFast document. Where prices differ, the detailed price list is used. Battery and solar prices are provisionally treated as VAT-inclusive consumer prices; confirm installation and included work. Heat pumps and Zaptec include 21% VAT. Some document totals contain arithmetic discrepancies; here the total is the VAT-exclusive price × 1.21 − subsidy. Subsidies are document estimates.')}</p><a href="/solarfast-brondocument.txt" download>{t('Volledig brondocument downloaden (Nederlands)','Download the complete source document (Dutch)')}</a></details>
  {editing!==undefined&&<ProductEditor initial={editing??undefined} onSave={onSaveProduct} onClose={()=>setEditing(undefined)}/>}
 </div>;
}
