import type {Profile} from './types';
import {useText,NumberField,Field,Toggle,Note} from './ui';
export function ProfileForm({profile:p,onChange}:{profile:Profile;onChange:(p:Profile)=>void}){
 const {t}=useText(); const set=(k:keyof Profile,v:number|string|boolean)=>onChange({...p,[k]:v});
 const input=(key:keyof Profile,nl:string,en:string,helpNl?:string,helpEn?:string,min=0,max=1e8)=><NumberField label={t(nl,en)} help={helpNl?t(helpNl,helpEn??helpNl):undefined} value={p[key] as number} onChange={v=>set(key,v??0)} min={min} max={max}/>;
 return <div className="sf-stack">
  <Note>{t('Voorbeeldgegevens staan alvast ingevuld. Gebruik je jaarafrekening voor een persoonlijk resultaat. Bestaande zonnepanelen tellen als uitgangspunt; voeg alleen nieuwe producten toe aan je plan.','Example values are prefilled. Use your annual statement for a personal estimate. Existing panels are your starting point; only add new products to your plan.')}</Note>
  <section className="sf-panel"><div className="sf-panel-title"><span className="sf-number">01</span><div><h2>{t('Stroom & zonnepanelen','Electricity & solar')}</h2><p>{t('Wat verbruik en produceer je nu?','What do you use and generate today?')}</p></div></div><div className="sf-fields">
  {input('electricity','Totaal stroomverbruik (kWh/jaar)','Total electricity use (kWh/year)','Inclusief direct gebruikte zonnestroom. Exclusief nieuw elektrisch verwarmen en de laadbehoefte hieronder.','Include directly used solar energy. Exclude new electric heating and the charging demand below.')}
  {input('solar','Bestaande zonneproductie (kWh/jaar)','Existing solar generation (kWh/year)','Geen zonnepanelen? Vul 0 in.','No panels? Enter 0.')}
  {input('exported','Huidige teruglevering (kWh/jaar)','Current exports (kWh/year)')}
  {input('electricityRate','Stroomprijs (€/kWh)','Electricity price (€/kWh)')}
  {input('exportRate','Terugleververgoeding (€/kWh)','Export payment (€/kWh)')}
  {input('fixedElectricity','Vaste stroomkosten (€/jaar)','Fixed electricity costs (€/year)')}
  </div><details><summary>{t('Terugleverkosten & saldering','Export fees & net metering')}</summary><div className="sf-fields sf-top"><Field label={t('Hoe betaal je terugleverkosten?','How are your export fees charged?')}><select value={p.feeMode} onChange={e=>set('feeMode',e.target.value)}><option value="kwh">{t('Per kWh','Per kWh')}</option><option value="annual">{t('Vast bedrag per jaar','Fixed annual amount')}</option></select></Field>{p.feeMode==='kwh'?input('exportFee','Terugleverkosten (€/kWh)','Export fees (€/kWh)'):input('fixedExportFee','Terugleverkosten (€/jaar)','Export fees (€/year)')}</div><Toggle label={t('Rekenen met volledige jaarlijkse saldering','Calculate with full annual net metering')} checked={p.netMetering} onChange={v=>set('netMetering',v)} help={t('Uit: teruglevering krijgt de ingevulde vergoeding. Aan: teruglevering wordt eerst verrekend met netafname. Hetzelfde beleid geldt voor vóór en na.','Off: exports receive the entered export payment. On: exports are first offset against grid imports. The same policy applies before and after.')}/></details></section>
  <section className="sf-panel"><div className="sf-panel-title"><span className="sf-number">02</span><div><h2>{t('Verwarming & vervoer','Heating & transport')}</h2><p>{t('Ook zonder warmtepomp of laadpaal vormt dit je huidige situatie.','These describe your current situation, even without a new heat pump or charger.')}</p></div></div><div className="sf-fields">
   {input('gas','Gasverbruik (m³/jaar)','Gas use (m³/year)','Zonder gas: 0. Het warmtepompmodel vervangt gasverwarming.','No gas: 0. The heat-pump model replaces gas heating.')}{input('gasRate','Gasprijs (€/m³)','Gas price (€/m³)')}{input('fixedGas','Vaste gaskosten (€/jaar)','Fixed gas costs (€/year)')}
   {input('evKwh','Publiek laden dat naar huis verhuist (kWh/jaar)','Public charging moving home (kWh/year)','Alleen laden dat nu nog niet in je stroomverbruik zit. 0 als je geen elektrische auto hebt.','Only charging not already included in your electricity use. Enter 0 if you do not have an EV.')}{input('publicChargingRate','Huidige publieke laadprijs (€/kWh)','Current public charging price (€/kWh)')}
  </div></section>
  <section className="sf-panel"><details><summary>{t('Rekeninstellingen voor je adviseur','Calculation settings for your adviser')}</summary><Note>{t('Dit zijn aanpasbare modelaannames, geen gegarandeerde prestaties of opbrengsten per fabrikant.','These are adjustable modelling assumptions, not guaranteed performance or returns for any manufacturer.')}</Note><div className="sf-fields sf-top">
  {input('solarYield','Zonneopbrengst (kWh per kWp/jaar)','Solar yield (kWh per kWp/year)')}{input('solarDirect','Direct gebruik nieuwe zonnestroom (%)','Direct use of new solar energy (%)',undefined,undefined,0,100)}
  {input('usableBattery','Bruikbaar deel batterij (%)','Usable battery capacity (%)',undefined,undefined,1,100)}{input('batteryEfficiency','Laad- en ontlaadrendement (%)','Round-trip efficiency (%)',undefined,undefined,1,100)}{input('batteryCycles','Volledige laadcycli per jaar','Full charge cycles per year',undefined,undefined,0,365)}
  {input('scop','Seizoensrendement warmtepomp (SCOP)','Heat pump seasonal efficiency (SCOP)',undefined,undefined,.1,10)}{input('hybridCoverage','Gasvervanging bij hybride (%)','Gas replacement for hybrid heating (%)',undefined,undefined,0,100)}{input('gasHeat','Nuttige warmte per m³ gas (kWh)','Useful heat per m³ gas (kWh)')}
  {input('annualInflation','Prijsstijging voor prognose (%/jaar)','Price increase for projection (%/year)',undefined,undefined,0,20)}{input('annualDegradation','Afbouw jaarvoordeel in prognose (%)','Annual benefit reduction in projection (%)',undefined,undefined,0,100)}
  </div><Toggle label={t('Extra handel via dynamische prijzen meenemen','Include additional trading at dynamic prices')} checked={p.dynamic} onChange={v=>set('dynamic',v)} help={t('Alleen de resterende laadcycli worden gebruikt, na opslag van zonnestroom. Tarieven hieronder zijn inclusief belastingen en kosten.','Uses only the remaining charge cycles after storing solar energy. Rates below must include taxes and fees.')}/>{p.dynamic&&<div className="sf-fields sf-top">{input('lowRate','Totale inkoopprijs tijdens laden (€/kWh)','Total purchase price when charging (€/kWh)')}{input('highRate','Netto verkoopopbrengst tijdens ontladen (€/kWh)','Net sale proceeds when discharging (€/kWh)')}</div>}</details></section>
 </div>;
}
