import type {Project} from './types';
import {calculateProject,epexCyclesForCapacity,EPEX_SPREAD_EUR_PER_KWH,EPEX_ROUND_TRIP_EFFICIENCY} from './engine';
import {useText,Field,Note,CategoryIcon,Button} from './ui';
import {Printer,Download,Mail} from 'lucide-react';
export function downloadProject(project:Project){const blob=new Blob([JSON.stringify(project,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='solarfast-energieplan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function Report({project,onChange}:{project:Project;onChange:(p:Project)=>void}){
 const {t,money,num,lang,productName}=useText();const r=calculateProject(project);const c=project.customer;
 const set=(key:keyof Project['customer'],value:string)=>onChange({...project,customer:{...c,[key]:value}});
 const max=Math.max(...r.projection.map(x=>x.value),1),min=Math.min(...r.projection.map(x=>x.value),0);const y=(v:number)=>200-(v-min)/(max-min)*170;const points=r.projection.map((v,i)=>`${45+i*35},${y(v.value)}`).join(' ');
 const annualRows:[string,number,number,string][]=[
  [t('Stroom van het net','Electricity from the grid'),r.before.grid,r.after.grid,'kWh'],
  [t('Teruggeleverde stroom','Exported electricity'),r.before.exported,r.after.exported,'kWh'],
  [t('Gasverbruik','Gas use'),r.before.gas,r.after.gas,'m³'],
  [t('Zonneproductie','Solar generation'),r.before.production,r.after.production,'kWh'],
 ];
 const textReport=[`SolarFast — ${c.name||t('Energieplan','Energy plan')}`,`${t('Investering','Investment')}: ${money(r.investment)}`,`${t('Verwacht jaarvoordeel','Estimated annual benefit')}: ${money(r.annual)}`,...project.lines.map(l=>`${l.quantity} × ${productName(l.product)}: ${l.price===null?'—':money(l.price*l.quantity)}`),c.notes].join('\n');
 const canReport=project.lines.length>0&&r.valid;
 return <div className="sf-report">
  <div className="sf-actions sf-report-actions no-print"><Button secondary onClick={()=>downloadProject(project)}><Download size={17}/>{t('Plan downloaden','Download plan')}</Button><Button disabled={!canReport} onClick={()=>window.print()}><Printer size={17}/>{t('Print / bewaar PDF','Print / save PDF')}</Button></div>
  <details className="sf-panel no-print"><summary>{t('Klantgegevens toevoegen','Add client details')}</summary><div className="sf-fields sf-top">{([['name','Naam','Name'],['address','Adres','Address'],['email','E-mailadres','Email'],['adviser','Adviseur','Adviser'],['date','Rapportdatum','Report date']] as const).map(([key,nl,en])=><Field key={key} label={t(nl,en)}><input type={key==='date'?'date':key==='email'?'email':'text'} value={c[key]} maxLength={300} onChange={e=>{if(key!=='date'||e.target.value)set(key,e.target.value);}}/></Field>)}</div><Field label={t('Opmerkingen en afspraken','Notes and agreements')}><textarea value={c.notes} maxLength={5000} rows={3} onChange={e=>set('notes',e.target.value)}/></Field></details>
  <header className="sf-report-header"><div><span className="sf-eyebrow">SOLARFAST / {t('PERSOONLIJK ENERGIEPLAN','PERSONAL ENERGY PLAN')}</span><h2>{c.name?`${t('Het plan voor','The plan for')} ${c.name}`:t('Jouw woning. Jouw mogelijkheden.','Your home. Your possibilities.')}</h2><p>{[c.address,c.email].filter(Boolean).join(' · ')}</p></div><span className="sf-small">{new Date(c.date+'T12:00:00').toLocaleDateString(lang==='nl'?'nl-NL':'en-GB',{day:'numeric',month:'long',year:'numeric'})}{c.adviser&&<><br/>{t('Adviseur','Adviser')}: {c.adviser}</>}</span></header>
  {!canReport&&<Note warning>{t('Voeg producten toe, controleer je verbruiksgegevens en vul alle prijzen in om een compleet rapport te maken.','Add products, check your usage inputs and enter all prices to create a complete report.')}</Note>}
  <div className="sf-stat-grid sf-roi-stat-grid"><div className="sf-stat primary"><span>{t('Netto investering','Net investment')}</span><strong>{r.missing.length?'—':money(r.investment)}</strong><small>{t('Inclusief btw, na indicatieve subsidie','Including VAT, after estimated subsidy')}</small></div><div className="sf-stat"><span>{t('Verwacht jaarvoordeel','Estimated annual benefit')}</span><strong>{canReport?money(r.annual):'—'}</strong><small>{canReport?`${money(r.annual/12)} ${t('gemiddeld per maand','average per month')}`:'—'}</small></div><div className="sf-stat"><span>{t('ROI per jaar','Annual ROI')}</span><strong>{canReport&&r.investment>0&&r.annual>0?`${num(r.annual/r.investment*100)}%`:'—'}</strong><small>{t('Netto jaarvoordeel ÷ netto investering','Net annual benefit ÷ net investment')}</small></div><div className="sf-stat"><span>{t('Eenvoudige terugverdientijd','Simple payback period')}</span><strong>{r.payback===null?'—':num(r.payback)}{r.payback!==null&&<em>{t('jaar','years')}</em>}</strong><small>{r.payback===null?t('Niet berekenbaar zonder positief jaarvoordeel en complete prijzen.','Requires positive annual benefit and complete prices.'):t('Netto investering ÷ jaarvoordeel','Net investment ÷ annual benefit')}</small></div></div>
  <section className="sf-panel"><div className="sf-between"><h2>{t('Dit komt er bij.','What you are adding.')}</h2><span className="sf-small">{project.lines.reduce((n,l)=>n+l.quantity,0)} {t('onderdelen','items')}</span></div><div className="sf-table-scroll"><table className="sf-table"><thead><tr><th>{t('Product','Product')}</th><th>{t('Aantal','Qty')}</th><th>{t('Bruto incl. btw','Gross incl. VAT')}</th><th>{t('Subsidie','Subsidy')}</th><th>{t('Netto','Net')}</th><th>{t('Bijdrage / jaar','Contribution / year')}</th></tr></thead><tbody>{r.contributions.map(({line:l,benefit,investment})=><tr key={l.id}><th scope="row">{productName(l.product)}{l.product.phase&&<small>{l.product.phase}{t('-fase','-phase')}</small>}</th><td>{l.quantity}</td><td>{l.price===null?'—':money(l.price*l.quantity,2)}</td><td>{money(Math.min(l.price??0,l.subsidy)*l.quantity,2)}</td><td>{l.price===null?'—':money(investment,2)}</td><td>{r.valid?money(benefit,2):'—'}</td></tr>)}</tbody><tfoot><tr><th>{t('Totaal','Total')}</th><td></td><td>{money(r.gross,2)}</td><td>{money(r.subsidy,2)}</td><td>{r.missing.length?'—':money(r.investment,2)}</td><td>{r.valid?money(r.annual,2):'—'}</td></tr></tfoot></table></div><p className="sf-small">{t('De bijdrage wordt toegerekend in deze volgorde: zonnepanelen → warmtepomp → laadpaal → batterij → extra’s. Zo telt dezelfde besparing niet dubbel. De bijdrage is afhankelijk van de combinatie, niet het losstaande rendement van een product.','Contributions are allocated in this order: solar → heat pump → charger → battery → extras. This avoids counting the same saving twice. Each contribution depends on the combination, not on the standalone return of a product.')}</p></section>
  <div className="sf-two-col"><section className="sf-panel"><h2>{t('Voor & na, per jaar','Before & after, per year')}</h2><table className="sf-table sf-comparison"><thead><tr><th>{t('Onderdeel','Item')}</th><th>{t('Nu','Now')}</th><th>{t('Met plan','With plan')}</th></tr></thead><tbody>{annualRows.map(([label,b,a,unit])=><tr key={label}><th scope="row">{label}<small>{unit}</small></th><td>{num(b,0)}</td><td>{num(a,0)}</td></tr>)}<tr><th>{t('Energie + publiek laden','Energy + public charging')}<small>{t('Vóór handel en onderhoud','Before trading and maintenance')}</small></th><td>{money(r.before.supplierCost)}</td><td>{money(r.after.supplierCost)}</td></tr></tbody></table></section>
  <section className="sf-panel"><h2>{t('Zo is het voordeel opgebouwd','How the benefit adds up')}</h2><dl className="sf-totals"><div><dt>{t('Verschil energiekosten','Difference in energy costs')}</dt><dd>{money(r.before.supplierCost-r.withoutBatteries.supplierCost,2)}</dd></div>{project.lines.some(l=>l.product.category==='battery')&&<><div><dt>☀️ {t('Zonne-optimalisatie batterij','Battery solar optimisation')}</dt><dd>{money(r.batteryOptimization.solarValue,2)}</dd></div><div><dt>⚡ {t('EPEX / EMS batterij','Battery EPEX / EMS')}</dt><dd>{project.profile.dynamic?money(r.batteryOptimization.epexValue,2):t('Niet actief','Not active')}</dd></div><div><dt>{t('Totale batterijwaarde','Total battery value')}</dt><dd>{money(r.batteryOptimization.totalAnnualValue,2)}</dd></div></>}{!project.lines.some(l=>l.product.category==='battery')&&<div><dt>{t('Aanvullende dynamische handel','Additional dynamic trading')}</dt><dd>{money(r.after.trading,2)}</dd></div>}<div><dt>{t('Handmatig ingevuld voordeel','Manually entered benefit')}</dt><dd>{money(r.after.manual,2)}</dd></div><div><dt>{t('Onderhoud & abonnementen','Maintenance & subscriptions')}</dt><dd>− {money(r.after.maintenance,2)}</dd></div><div className="sf-total"><dt>{t('Verwacht jaarvoordeel','Estimated annual benefit')}</dt><dd>{money(r.annual,2)}</dd></div></dl>{project.lines.some(l=>l.product.category==='battery')&&<p className="sf-small">{t('EPEX voordeel wordt berekend op basis van batterijcapaciteit, actieve cycli, gemiddelde prijsverschillen en batterijrendement. Het resultaat is een indicatieve optimale marktberekening en geen gegarandeerde opbrengst.','EPEX value is calculated from battery capacity, active cycles, average price spreads and battery efficiency. This is an indicative optimal-market calculation, not a guaranteed return.')}</p>}</section></div>
  {canReport&&<section className="sf-panel sf-projection"><div className="sf-between"><div><span className="sf-eyebrow">{t('VOORUITKIJKEN','LOOKING AHEAD')}</span><h2>{t('Een plan voor de langere termijn.','A plan for the longer term.')}</h2></div><div><strong>{money(r.projection[10].value)}</strong><small>{t('cumulatief na 10 jaar','cumulative after 10 years')}</small></div></div><svg viewBox="0 0 620 245" role="img" aria-label={t('Cumulatief resultaat over 15 jaar na aftrek van de investering','Cumulative result over 15 years after investment')}><line x1="45" y1={y(0)} x2="580" y2={y(0)} stroke="#a9b7a9" strokeDasharray="4 4"/><polyline points={points} fill="none" stroke="#1d6048" strokeWidth="3"/>{[0,5,10,15].map(i=><g key={i}><circle cx={45+i*35} cy={y(r.projection[i].value)} r="4" fill="#1d6048"/><text x={45+i*35} y="233" textAnchor="middle" fill="#69766e" fontSize="12">{i} {t('jaar','years')}</text><text x={45+i*35} y={y(r.projection[i].value)-10} textAnchor="middle" fill="#1d6048" fontSize="12">{money(r.projection[i].value)}</text></g>)}</svg><p className="sf-small">{t('Na aftrek van investering en ingevuld jaarlijks onderhoud.','After investment and the annual maintenance entered.')} {num(project.profile.annualInflation)}% {t('prijsstijging en','price increase and')} {num(project.profile.annualDegradation)}% {t('afbouw van jaarvoordeel per jaar. Zonder vervangingskosten of financieringskosten. Een prognose, geen garantie.','annual benefit reduction. Excludes replacement and financing costs. A projection, not a guarantee.')}</p></section>}
  {project.finance.enabled&&<section className="sf-panel"><h2>{t('Financiering in je plan','Financing in your plan')}</h2><div className="sf-finance-figures"><div><span>{t('Lening','Loan')}</span><strong>{money(r.financed)}</strong></div><div><span>{t('Maandlast','Monthly payment')}</span><strong>{money(r.monthlyPayment,2)}</strong></div><div><span>{t('Voordeel min maandlast','Benefit less monthly payment')}</span><strong>{money(r.monthlyNet,2)}</strong></div></div><p className="sf-small">{num(project.finance.rate)}% · {project.finance.years} {t('jaar','years')} · {t('Totaal rente','Total interest')}: {money(r.loanTotal-r.financed,2)}. {t('Geen goedkeuring of offerte voor een lening.','Not a loan approval or quotation.')}</p></section>}
  <section className="sf-panel sf-report-assumptions"><h2>{t('Uitgangspunten van dit plan','Assumptions used in this plan')}</h2><div className="sf-assumption-grid"><p>{t('Stroomprijs','Electricity rate')}: {money(project.profile.electricityRate,3)}/kWh<br/>{t('Gasprijs','Gas rate')}: {money(project.profile.gasRate,3)}/m³<br/>{t('Terugleververgoeding','Export payment')}: {money(project.profile.exportRate,3)}/kWh<br/>{t('Saldering','Net metering')}: {project.profile.netMetering?t('aan','on'):t('uit','off')}</p><p>{t('Zonnebatterijrendement','Solar battery efficiency')}: {num(project.profile.batteryEfficiency)}%<br/>{t('Bruikbare capaciteit','Usable capacity')}: {num(project.profile.usableBattery)}%<br/>{t('Zonne-opslagcycli','Solar storage cycles')}: {num(project.profile.batteryCycles)}<br/>{t('Dynamische handel','Dynamic trading')}: {project.profile.dynamic?t('aan','on'):t('uit','off')}{project.profile.dynamic&&project.lines.some(l=>l.product.category==='battery')&&<><br/>EPEX: {num(epexCyclesForCapacity(r.after.nominalCapacity))} {t('cycli/jaar','cycles/year')} × {money(EPEX_SPREAD_EUR_PER_KWH,2)}/kWh × {num(EPEX_ROUND_TRIP_EFFICIENCY*100)}% {t('rendement','efficiency')}</>}</p><p>SCOP: {num(project.profile.scop)}<br/>{t('Hybride gasvervanging','Hybrid gas replacement')}: {num(project.profile.hybridCoverage)}%<br/>{t('Zonneopbrengst','Solar yield')}: {num(project.profile.solarYield)} kWh/kWp<br/>{t('Direct gebruik nieuwe zon','Direct use of new solar')}: {num(project.profile.solarDirect)}%</p></div><p className="sf-small">{t('Jaarmodel; geen simulatie op kwartierdata. Compatibiliteit, aansluitvermogen, dakopbrengst, warmteverlies en subsidie moeten voor een offerte worden gecontroleerd. EPEX is indicatief berekend als nominale batterijcapaciteit × capaciteitsspecifieke cycli × €0,20/kWh prijsverschil × 90% rendement; werkelijke marktresultaten kunnen afwijken. Zonne-opslag en EPEX zijn apart gemodelleerd. Meerdere warmtepompen of laadpalen vermenigvuldigen de warmtevraag of laadbehoefte niet.','Annual model, not a simulation using interval data. Compatibility, connection capacity, roof yield, heat loss and subsidy must be checked before quoting. EPEX is an indicative model: nominal battery capacity × capacity-specific cycles × €0.20/kWh spread × 90% efficiency; actual market results may differ. Solar storage and EPEX are modelled separately. Multiple heat pumps or chargers do not multiply heating or charging demand.')}</p></section>
  {c.notes&&<section className="sf-panel"><h2>{t('Afspraken & opmerkingen','Agreements & notes')}</h2><p className="sf-preserve">{c.notes}</p></section>}
  <Note>{t('Indicatieve berekening op basis van ingevoerde prijzen, verbruik en aannames. Werkelijke resultaten kunnen afwijken. Subsidies zijn niet toegezegd.','Indicative calculation based on entered prices, usage and assumptions. Actual results may differ. Subsidies are not guaranteed.')}</Note>
  <div className="sf-contact-strip no-print"><div><h2>{t('Van plan naar persoonlijk advies.','From your plan to personal advice.')}</h2><p>{t('Bespreek je samenstelling met SolarFast.','Discuss your configuration with SolarFast.')}</p></div><a className={`sf-button ${!canReport?'disabled':''}`} aria-disabled={!canReport} onClick={e=>{if(!canReport)e.preventDefault();}} href={`mailto:info@solarfast.nl?subject=${encodeURIComponent(t('Mijn SolarFast energieplan','My SolarFast energy plan'))}&body=${encodeURIComponent(textReport)}`}><Mail size={18}/>{t('Open e-mail met mijn plan','Open email with my plan')}</a></div>
 </div>;
}
